/** Public result shapes for the fact-check API.
 *
 *  The verdict vocabulary itself lives in ./schema.ts and is re-exported here
 *  so existing importers keep working. There is exactly ONE definition of what
 *  a verdict is; this file must never declare its own. */

export type { Verdict, EvidenceStrength, SourceTier, Stance, Basis } from './schema';
import type { Basis, EvidenceStrength, SourceTier, Stance, Verdict } from './schema';

/** One cited source, as it was actually used.
 *
 *  Every field beyond title/url/publisher was added in Phase 3. The previous
 *  shape could not express when a source was published, what it said about the
 *  claim, how reliable it was, or whether we managed to read it — so the
 *  interface could show a citation without showing whether it supported
 *  anything. */
export interface Evidence {
  title: string;
  url: string;
  publisher: string;
  /** The publisher's own rating, on the certified path only. */
  rating?: string;

  /** Display order, and the [1] [2] [3] the reasoning cites. */
  position?: number;
  /** Normalised registrable domain; independence is counted on this. */
  domain?: string;
  tier?: SourceTier;
  /** What this source says about the claim. Independent of tier. */
  stance?: Stance;
  /** Publication date. null/absent means genuinely unknown — never inferred,
   *  and never back-filled from accessedAt. */
  publishedAt?: string | null;
  /** When NewzWale read it. Always known. */
  accessedAt?: string;
  /** The exact text relied on, so a reader can check our reading. */
  quotedPassage?: string;
  /** Whether the page was read in full or only a search snippet was available. */
  readMethod?: 'full_page' | 'search_snippet';
  /** True when this source tried to manipulate the assessment. Surfaced, not
   *  hidden: a reader is entitled to know. */
  injectionFlagged?: boolean;

  // ── Phase 4. Needed by the future result page (4Q). ──

  /** False when the passage does not materially address the claim. Such an
   *  item is still shown — the reader should see what was read — but it did
   *  not count toward corroboration. */
  relevant?: boolean;
  relevanceLevel?: 'high' | 'medium' | 'low' | 'none';
  /** What the stance classifier said before deterministic validation. */
  claimedStance?: Stance;
  /** True when validation overruled the classifier for this source. */
  stanceDemoted?: boolean;
}

/** Two credible sources materially disagreeing with each other.
 *  Reported, never averaged away. */
export interface SourceDisagreement {
  positions: number[];
  point: string;
  significance: 'material' | 'minor';
}

export interface FactCheckResult {
  verdict: Verdict;
  /** The one-line answer followed by any limitations. Retained under this name
   *  so the existing widget keeps rendering without change. */
  explanation: string;
  evidence: Evidence[];
  /** 'certified' = a published fact-checker reviewed this claim.
   *  'ai_assessment' = generated by a model over retrieved passages.
   *  'none' = nothing was established. */
  basis: Basis;

  // ── Phase 3 additions. Optional so older payloads still parse. ──

  /** Stable, shareable id: sha256(normalised claim | pipeline identity). */
  id?: string;
  /** The claim as extracted and judged — not necessarily as submitted. */
  claim?: string;
  /** Independent of the verdict, and always displayed alongside it. */
  evidenceStrength?: EvidenceStrength;
  /** One-line answer. */
  summary?: string;
  /** Why this verdict, citing evidence positions. */
  reasoning?: string;
  /** What could NOT be established, including every deterministic downgrade. */
  limitations?: string[];
  /** What the model proposed, retained even when the gate overrode it. */
  proposedVerdict?: Verdict;
  /** True when deterministic rules overruled the model. */
  gateOverrode?: boolean;
  /** Machine-readable rule ids that fired, for analytics and debugging. */
  gateRules?: string[];
  /** Disagreements between sources, surfaced rather than resolved. */
  disagreements?: SourceDisagreement[];
  independentSupportingDomains?: number;
  independentContradictingDomains?: number;
  /** Reproducibility triple. */
  pipelineVersion?: number;
  evidenceVersion?: number;
  modelId?: string;
  checkedAt?: string;
}
